# Generated by Django 4.1.1 on 2022-09-23 07:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('si_no', models.IntegerField()),
                ('month', models.CharField(max_length=50, unique=True)),
                ('business_type', models.CharField(max_length=100)),
                ('posters', models.CharField(max_length=60)),
                ('followers', models.IntegerField()),
                ('leads', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('page_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('si_no', models.IntegerField()),
                ('month', models.CharField(max_length=200, unique=True)),
                ('business_type', models.CharField(max_length=100)),
                ('posters', models.CharField(max_length=60)),
                ('followers', models.IntegerField()),
                ('leads', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('feedback', models.CharField(max_length=200)),
                ('page_id', models.CharField(max_length=50)),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.requirements')),
            ],
        ),
    ]
